apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ai-ext-config
data:
  PAPERLESS_AIEXT_LISTEN_ADDR: :8080
  PAPERLESS_AIEXT_LOGLEVEL: info
  PAPERLESS_AIEXT_PRETTY_LOGS: "false"
  PAPERLESS_URL: https://paperless.example.com